version: '3.8'

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - ALLOW_ORIGINS=*
      - OPENAI_API_KEY=tu-clave
      - MODEL=tu-modelo
      - EMBEDDING_MODEL=tu-embedding
      - EMBEDDING_DIMENSIONS=768
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCS_DIR=/home/data/docs
      - EXPORT_DIR=/home/data/export
    expose:
      - "8000"
    networks:
      - backend

  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 600 1 --save 300 10 --save 60 100
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend:
